
main: clean
	javac Main.java

run:
	java Main

clean:
	find . -type f -name "*.class" -delete
	find . -type f -name "*.ctxt" -delete
	find . -type f -name "package.bluej" -delete

removeSaves:
	rm ObjectSaves/estadoObj.obj