#Simple makefile

#Compile main program
main:
	javac Main.java
	
#Main - IO version	
io:
	javac Main_IO.java

#Run the program
run:
	java Main

#Run the IO version
runio:
	java Main_IO

#Clean .class files
clean: 
	rm *.class *.ctxt
